[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "https://makethingsaccessible.co.uk/*"
  to = "https://makethingsaccessible.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ap"
  to = "/rnib/accessibility-Passport"
  status = 301
  force = true