backend:
  name: git-gateway
  branch: main
  repo: LDAWG-a11y/a11yWebApp
media_folder: "src/img"
public_folder: "src/img"
publish_mode: editorial_workflow
collections:
  - name: "guides"
    label: "Guides"
    folder: "/src/guides"
    media_folder: "/src/guideImg"
    public_folder: "/guideImg"
    slug: "{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Try to keep this short and meaningful" }
      - { label: "Summary", name: "summary", widget: "string", hint: "This is displayed on the Guide card, it is also used for the page description, for SEO purposes" }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", value_field: "key", display_fields: [ "name.first", "name.last" ], search_fields: [ "name.first", "name.last" ], default: "Admin", hint: "New authors need to be created before a guide can be attributed to them "}
      - { label: "Date", name: "date", widget: "datetime", format: 'YYYY-MM-DD', hint: "Change this only if you update your guide"}
      - { label: "Table of Contents (TOC)", name: "toc", widget: "boolean", default: false, hint: "Only add a TOC if there 4 or more heading 2s" }
      - { label: "Tags", name: "tags", widget: "list", hint: "Tags are case sensitive, so html and HTML are not the same tag, so please ensure you have checked a tag exists, before creating a new one, as a typo or case mismatch will cause a system error", default: Untagged, summary: "{{fields.tag}}", field: { label: "Tag", name: "tag", widget: "string" }}
      - { label: "Include files", name: "file", widget: "file", required: false, media_folder: "/src/docs", public_folder: "/public/docs", media_library: {config: {multiple: true}} }
      - { label: "Page content", name: "body", widget: "markdown" }
      - { label: "isGuide", name: "isGuide", default: true, widget: "hidden" }
  - name: "authors"
    label: "Authors"
    create: true
    format: json
    identifier_field: name
    folder: "/src/_data/contributors"
    media_folder: "/src/guideImg/profileImg"
    public_folder: "/guideImg/profileImg"
    fields:
      - { label: "Username", name: "key", widget: "string", hint: "This is not displayed anywhere but the URL, it needs to be unique and can only contain alphanumeric characters, e.g: jBloggs1" }
      - name: "name"
        widget: "list"
        fields: 
          - { label: "First Name", name: first, widget: string, hint: "Your first name"}
          - { label: "Last Name", name: last, widget: string, hint: "Your last name"}
      - { label: "Job Title", name: "title", widget: "string", required: false }
      - { label: "Organisation", name: "org", widget: "string", required: false }
      - { label: "Bio", name: "bio", widget: "text", hint: "Tell the world a bit about yourself" }
      - { label: "Profile picture", name: "img", widget: "image", required: false, hint: "This image needs to be square and it should be quite small, about 192px * 192px" }
      - { label: "Twitter handle", name: "twitter", widget: "string", required: false, hint: "Please paste in your full Twitter URL" }
      - { label: Email, name: "email", widget: "string", required: false }
      - { label: "LinkedIn", name: "linkedin", widget: "string", required: false, hint: "Please paste in your full LinkedIn URL" }
      - { label: "Tags", name: "tags", default: "contributors", widget: "hidden" }
      - label: 'Website'
        name: "website"
        widget: "list"
        required: false
        fields:
          - { label: "Website URL", name: "url", widget: "string", hint: "Example: https://www.yoursite.com" }
          - { label: "Website Name", name: "name", widget: "string", hint: "Example: yoursite.com" }
  - name: "faqs"
    label: "FAQs"
    folder: "/src/faqs"
    create: true
    delete: true
    media_folder: "/src/faqImg"
    public_folder: "/faqImg"
    fields:
      - { label: "Question", name: "title", widget: "string", hint: "The title is displayed in an accordion button"}
      - { label: "Answer", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", format: 'YYYY-MM-DD', widget: "datetime", hint: "This should be changed if the page is edited" }
      - { label: "Tags", name: "tags", default: "faqs", widget: "hidden" }
      - { label: "Include files", name: "file", widget: "file", required: false, media_folder: "/src/docs", public_folder: "/docs", media_library: {config: {multiple: true}} }
      - { label: "Permalink", name: "permalink", default: false, widget: "hidden" }
  - name: "terms"
    label: "Glossary"
    folder: "/src/terms"
    create: true
    delete: true      
    fields:
      - { label: "Term", name: "title", widget: "string", hint: "Initialism, Acronym, technical term etc" }
      - { label: "Acronym?", name: "acronym", widget: "boolean", default: false, hint: "Toggle to true if this is an acronym" }
      - { label: "Definition", name: "body", widget: "text" }
      - { label: "Permalink", name: "permalink", default: false, widget: "hidden" }
      - { label: "Date", name: "date", format: 'YYYY-MM-DD', widget: "datetime", hint: "This should be changed if you add a new item" }
      - { label: "Tags", name: "tags", default: "terms", widget: "hidden" }
  - name: "pages"
    label: "Pages (MTA)"
    files:
      - label: "Accessibility Statement"
        name: "accessibility"
        file: "/src/accessibility.md"
        fields:
          - { label: "Table of Contents (TOC)", name: "toc", widget: "boolean", default: false, hint: "Only add a TOC if there 4 or more heading 2s" }
          - { label: "Date", name: "date", format: 'YYYY-MM-DD', widget: "datetime", hint: "This should be changed if the page is edited" }
          - { label: "Page content", name: body, widget: markdown, hint: "The page already has a H1, so if starting with a heading it needs to be a H2" }
      - label: "About Page"
        file: "/src/about.md"
        name: "about"
        fields:
          - { label: "Date", name: "date", format: 'YYYY-MM-DD', widget: "datetime", hint: "This should be changed if the page is edited" }
          - {label: "Page content", name: body, widget: markdown, hint: "The page already has a H1, so if starting with a heading it needs to be a H2" }
      - label: "Privacy policy"
        name: "privacy"
        file: "/src/privacy.md"
        fields:
          - { label: "Table of Contents (TOC)", name: "toc", widget: "boolean", default: false, hint: "Only add a TOC if there 4 or more heading 2s" }
          - { label: "Date", name: "date", format: 'YYYY-MM-DD', widget: "datetime", hint: "This should be changed if the page is edited" }
          - { label: "Page content", name: body, widget: markdown, hint: "The page already has a H1, so if starting with a heading it needs to be a H2" }
      - label: "Code of Conduct"
        name: "codeOfConduct"
        file: "/src/codeOfConduct.md"
        fields:
          - { label: "Table of Contents (TOC)", name: "toc", widget: "boolean", default: false, hint: "Only add a TOC if there 4 or more heading 2s" }
          - { label: "Date", name: "date", format: 'YYYY-MM-DD', widget: "datetime", hint: "This should be changed if the page is edited" }
          - { label: "Page content", name: body, widget: markdown, hint: "The page already has a H1, so if starting with a heading it needs to be a H2" }
      - label: "Contributing"
        name: "contributing"
        file: "/src/contributing.md"
        fields:
          - { label: "Table of Contents (TOC)", name: "toc", widget: "boolean", default: false, hint: "Only add a TOC if there 4 or more heading 2s" }
          - { label: "Date", name: "date", format: 'YYYY-MM-DD', widget: "datetime", hint: "This should be changed if the page is edited" }
          - { label: "Page content", name: body, widget: markdown, hint: "The page already has a H1, so if starting with a heading it needs to be a H2" }
      - label: "Home"
        name: "home"
        file: "/src/index.njk"
        fields:
          - { label: "Page content", name: body, widget: markdown, hint: "The page already has a H1, so if starting with a heading it needs to be a H2" }
  - name: "aaapages"
    label: "AAA Pages"
    files:
      - label: "AAA Home"
        name: "aaaHome"
        file: "/src/AAA/index.md"
        media_folder: "/src/aaaAssets"
        public_folder: "/aaaAssets"
        fields:
          - { label: "Date", name: "date", format: 'YYYY-MM-DD', widget: "datetime", hint: "This should be changed if the page is edited" }
          - { label: "Include files", name: "file", widget: "file", required: false, media_folder: "/src/aaaDocs", public_folder: "/aaaDocs", media_library: {config: {multiple: true}} }
          - {label: "Page content", name: body, widget: markdown, hint: "The page already has a H1, so if starting with a heading it needs to be a H2" }
      - label: "AAA Roles"
        name: "roles"
        file: "/src/AAA/roles.md"
        media_folder: "/src/aaaAssets"
        public_folder: "/aaaAssets"
        fields:
          - { label: "Date", name: "date", format: 'YYYY-MM-DD', widget: "datetime", hint: "This should be changed if the page is edited" }
          - { label: "Include files", name: "file", widget: "file", required: false, media_folder: "/src/aaaDocs", public_folder: "/aaaDocs", media_library: {config: {multiple: true}} }
          - {label: "Page content", name: body, widget: markdown, hint: "The page already has a H1, so if starting with a heading it needs to be a H2" }
      - label: "AAA Assistive Tech"
        name: "aaa-at"
        file: "/src/AAA/aaa-at.md"
        media_folder: "/src/aaaAssets"
        public_folder: "/aaaAssets"
        fields:
          - { label: "Date", name: "date", format: 'YYYY-MM-DD', widget: "datetime", hint: "This should be changed if the page is edited" }
          - { label: "Include files", name: "file", widget: "file", required: false, media_folder: "/src/aaaDocs", public_folder: "/aaaDocs", media_library: {config: {multiple: true}} }
          - {label: "Page content", name: body, widget: markdown, hint: "The page already has a H1, so if starting with a heading it needs to be a H2" }
      - name: "aaaSupporters"
        label: "AAA Supporters"
        file: "/src/AAA/supporters.md"
        media_folder: "/src/aaaAssets"
        public_folder: "/aaaAssets"
        fields:
          - { label: "Page content", name: "body", widget: "markdown", hint: "Only use the Logo Link option to add a supporter" }
  - name: "aaaStories"
    label: "AAA Stories"
    folder: "/src/AAA/aaaStories"
    media_folder: "/src/aaaAssets"
    public_folder: "./src/aaaAssets"
    slug: "{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Try to keep this short and meaningful", pattern: ['^.{0,80}$', 'Must not exceed 80 characters']}
      - { label: "Summary", name: "summary", widget: "string", hint: "This is displayed in search engine results, for SEO purposes", pattern: ['^.{0,200}$', 'Must not exceed 200 characters'] }
      - { label: "Card image", name: "img", widget: "image", hint: "Landscape shape, omitting this will display AAA logo", required: false }
      - { label: "Date", name: "date", widget: "datetime", format: 'YYYY-MM-DD', hint: "Change this only if you update your guide"}
      - { label: "Table of Contents (TOC)", name: "toc", widget: "boolean", default: false, hint: "Only add a TOC if there 4 or more heading 2s" }
      - { label: "Include files", name: "file", widget: "file", required: false, media_folder: "/src/aaaDocs", public_folder: "/aaaDocs", media_library: {config: {multiple: true}} }
      - { label: "Page content", name: "body", widget: "markdown" }
      - { label: "isGuide", name: "isGuide", default: true, widget: "hidden" }